---
# location and name of todo.txt
TODO:
  PATH: "C:/.../todo_txt"
  FILE: "todo.txt"
# location and name of todo.txt archive
# when PATH is empty TODO.PATH will be used  
ARCHIVE: 
  PATH: "C:/.../todo_txt"
  FILE: "todo_done.txt"
# location and name of todo.txt back up files
# when PATH is empty TODO.PATH will be used
BACKUP: 
  PATH: "C:/.../todo_backup"
  FILE: "todo_backup.bak"
  ARCHIVE: "archive_backup.bak"
# default settings 
SETTINGS:
  SHOW_INFO: true # display verbose information
  COLOR_MAP: TODO_COLORS_BG_WHITE # must match to one of the TODO_COLORS_... profiles
  DATE_CHANGED: true # add changed_date attribute
# color code table see 
# Repo: tools_console > console_utils.py
# https://stackoverflow.com/questions/287871/how-do-i-print-colored-text-to-the-terminal
COLORS:
  COLOR_DICT:
    COLOR_DEFAULT: "1;37;47"
    COLOR_DEFAULT_BG: "1;37;47"
    COLOR_GREY: "1;30;40"
    COLOR_RED: "1;31;40"
    COLOR_GREEN: "1;32;40"
    COLOR_YELLOW: "1;33;40"
    COLOR_BLUE: "1;34;40"
    COLOR_PURPLE: "1;35;40"
    COLOR_LIGHTBLUE: "1;36;40"
    COLOR_WHITE: "1;37;40"
    COLOR_RED_BG: "1;31;41"
    COLOR_GREEN_BG: "1;37;42"
    COLOR_YELLOW_BG: "1;37;43"
    COLOR_BLUE_BG: "1;37;44"
    COLOR_PURPLE_BG: "1;37;45"
    COLOR_LIGHTBLUE_BG: "1;37;46"
    COLOR_WHITE_BG: "1;37;47"
    COLOR_GREY_WH: "1;30;47"
    COLOR_RED_WH: "1;31;47"
    COLOR_GREEN_WH: "1;32;47"
    COLOR_YELLOW_WH: "1;33;47"
    COLOR_BLUE_WH: "1;34;47"
    COLOR_PURPLE_WH: "1;35;47"
    COLOR_LIGHTBLUE_WH: "1;36;47"
    COLOR_BLACK_WH: "1;30;47"
 # customize the task colors refer to one of the values in COLOR_LIST      
  # TODO COLORS DEFAULT      
  TODO_COLORS_DEFAULT:
    DEFAULT_COLOR: COLOR_DEFAULT
    COMPLETE: COLOR_GREEN
    PRIO: COLOR_PURPLE
    DATE_COMPLETED: COLOR_GREEN
    DATE_CREATED: COLOR_LIGHTBLUE
    DESCRIPTION: COLOR_DEFAULT
    LINKS: COLOR_LIGHTBLUE
    PROJECTS: COLOR_PURPLE
    CONTEXTS: COLOR_YELLOW
    ATTRIBUTES: COLOR_YELLOW
    DATE_CHANGED: COLOR_YELLOW
    HASH: COLOR_LIGHTBLUE
    ORIGINAL: COLOR_GREY  
  # TODO COLORS WHITE BACKGROUND
  TODO_COLORS_BG_WHITE:  
    DEFAULT_COLOR: COLOR_DEFAULT_WH
    COMPLETE: COLOR_GREEN_WH
    PRIO: COLOR_PURPLE_WH
    DATE_COMPLETED: COLOR_GREEN_WH
    DATE_CREATED: COLOR_LIGHTBLUE_WH
    DESCRIPTION: COLOR_DEFAULT_WH
    LINKS: COLOR_LIGHTBLUE_WH
    PROJECTS: COLOR_PURPLE_WH
    CONTEXTS: COLOR_YELLOW_WH
    ATTRIBUTES: COLOR_YELLOW_WH
    DATE_CHANGED: COLOR_YELLOW_WH
    HASH: COLOR_LIGHTBLUE_WH
    ORIGINAL: COLOR_GREY_WH  
  # TODO COLORS BLACK BACKGROUND
  TODO_COLORS_BG_BLACK:
    DEFAULT_COLOR: COLOR_DEFAULT_BG
    COMPLETE: COLOR_GREEN_BG
    PRIO: COLOR_PURPLE_BG
    DATE_COMPLETED: COLOR_GREEN_BG
    DATE_CREATED: COLOR_LIGHTBLUE_BG
    DESCRIPTION: COLOR_DEFAULT_BG
    LINKS: COLOR_LIGHTBLUE_BG
    PROJECTS: COLOR_PURPLE_BG
    CONTEXTS: COLOR_YELLOW_BG
    ATTRIBUTES: COLOR_YELLOW_BG
    DATE_CHANGED: COLOR_YELLOW_BG
    HASH: COLOR_LIGHTBLUE_BG
    ORIGINAL: COLOR_DEFAULT_BG
